# Generated by Django 3.1.6 on 2021-02-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Высота блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='num_trans_in_block',
            field=models.IntegerField(verbose_name='Количество транзакций в блоке'),
        ),
    ]
